Name:           perl-Net-SSH-Perl
Version:        2.14
Release:        1%{?dist}
Summary:        Perl client Interface to SSH
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-SSH-Perl/
Source0:        http://www.cpan.org/modules/by-module/Net/Net-SSH-Perl-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(Crypt::Curve25519) >= 0.05
BuildRequires:  perl(Crypt::IDEA)
BuildRequires:  perl(Crypt::RSA)
BuildRequires:  perl(CryptX) >= 0.032
BuildRequires:  perl(Digest::BubbleBabble)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::HomeDir)
BuildRequires:  perl(Math::GMP) >= 1.04
BuildRequires:  perl(Module::Signature) >= 0.50
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(String::CRC32) >= 1.2
BuildRequires:  perl(Term::ReadKey)
BuildRequires:  perl(Test::More) >= 0.61
Requires:       perl(Crypt::Curve25519) >= 0.05
Requires:       perl(Crypt::IDEA)
Requires:       perl(Crypt::RSA)
Requires:       perl(CryptX) >= 0.032
Requires:       perl(Digest::BubbleBabble)
Requires:       perl(File::HomeDir)
Requires:       perl(Math::GMP) >= 1.04
Requires:       perl(Module::Signature) >= 0.50
Requires:       perl(Scalar::Util)
Requires:       perl(String::CRC32) >= 1.2
Requires:       perl(Term::ReadKey)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Net::SSH::Perl is an all-Perl module implementing an SSH (Secure Shell)
client. It is compatible with both the SSH-1 and SSH-2 protocols.

%prep
%setup -q -n Net-SSH-Perl-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README ToDo
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Net*
%{_mandir}/man3/*

%changelog
* Tue Mar 19 2019 Johannes Grumboeck <johannes.grumboeck@porscheinformatik.at> 2.14-1
- Specfile autogenerated by cpanspec 1.78.
